on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Create Node.js script for Puppeteer
      run: |-
        cat << 'EOF' > fetchPage.js
        const fs = require('fs');
        const puppeteer = require('puppeteer');

        (async () => {
          try {
            const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
            const page = await browser.newPage();
            await page.goto('https://store.steampowered.com/sale/steamdeckrefurbished/', { waitUntil: 'networkidle0' });

            const content = await page.content();
            fs.writeFileSync('dump.html', content);

            if (content.trim().length === 0) {
              const timestamp = new Date().toISOString();
              fs.appendFileSync('steamdeck_error_log.txt', `Error at: ${timestamp}\n`);
            } else {
              console.log('Steam Deck Refurbished page fetched successfully.');
            }

            await browser.close();
          } catch (error) {
            const timestamp = new Date().toISOString();
            fs.appendFileSync('steamdeck_error_log.txt', `Error at: ${timestamp} - ${error.message}\n`);
            console.error(error);
          }
        })();
        EOF

    - name: Run Puppeteer script
      run: node fetchPage.js

    - name: Commit and push changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add dump.html steamdeck_error_log.txt || true
        git commit -m "Automated update at $(date +"%Y/%m/%d %H:%M")" || exit 0
        git push
